import { gql } from "@apollo/client";

export const GET_KPI_QUARTER_PERFORMANCE_REPORT = gql`
  query GetKpiQuarterPerformanceReport(
    $filters: KpiQuarterReportFiltersInput!
  ) {
    kpiQuarterPerformanceReport(filters: $filters) {
      annualStrategicPeriodId
      annualStrategicPeriodName
      scope
      availableFilters {
        divisions {
          id
          name
          parentId
          parentIds
        }
        departments {
          id
          name
          parentId
          parentIds
        }
        employees {
          id
          name
          parentId
          parentIds
        }
      }
      summary {
        rowCount
        kpiCount
        originalTarget
        carryIn
        effectiveTarget
        actual
        averageAchievementRate
        weightedAchievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        annualContribution
        carryOut
        finalCount
        provisionalCount
        pendingResultCount
      }
      quarterSummaries {
        quarterNumber
        rowCount
        kpiCount
        originalTarget
        carryIn
        effectiveTarget
        actual
        averageAchievementRate
        weightedAchievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        annualContribution
        carryOut
        finalCount
        provisionalCount
        pendingResultCount
      }
      rollups {
        level
        entityId
        entityName
        rowCount
        kpiCount
        originalTarget
        carryIn
        effectiveTarget
        actual
        averageAchievementRate
        weightedAchievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        annualContribution
        carryOut
        finalCount
        provisionalCount
        pendingResultCount
      }
      kpiRollups {
        kpiId
        kpiName
        objectiveId
        objectiveTitle
        objectiveWeight
        cascadeType
        parentKpiId
        measurementUnit
        unitType
        customUnitLabel
        quarterlyAggregationMethod
        calculationType
        annualTarget
        weight
        target
        actual
        achievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        planCount
        resultCount
      }
      entityQuarterRollups {
        quarterNumber
        level
        entityId
        entityName
        rowCount
        kpiCount
        originalTarget
        carryIn
        effectiveTarget
        actual
        averageAchievementRate
        weightedAchievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        annualContribution
        carryOut
        finalCount
        provisionalCount
        pendingResultCount
      }
      kpiQuarterRollups {
        quarterNumber
        kpiId
        kpiName
        objectiveId
        objectiveTitle
        objectiveWeight
        cascadeType
        parentKpiId
        measurementUnit
        unitType
        customUnitLabel
        quarterlyAggregationMethod
        calculationType
        annualTarget
        weight
        target
        actual
        achievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        planCount
        resultCount
      }
      entityKpiRollups {
        quarterNumber
        kpiId
        kpiName
        objectiveId
        objectiveTitle
        objectiveWeight
        cascadeType
        parentKpiId
        measurementUnit
        unitType
        customUnitLabel
        quarterlyAggregationMethod
        calculationType
        annualTarget
        weight
        target
        actual
        achievementRate
        plannedContributionWeight
        achievedContributionWeight
        resultCoverageRate
        planCount
        resultCount
        level
        entityId
        entityName
        divisionId
        divisionName
        departmentId
        departmentName
      }
      rows {
        kpiQuarterPlanId
        kpiId
        kpiName
        objectiveId
        objectiveTitle
        objectiveWeight
        cascadeType
        parentKpiId
        level
        entityId
        entityName
        divisionId
        divisionName
        departmentId
        departmentName
        employeeId
        employeeName
        kpiMode
        aggregationMethod
        weightingBasisKpiId
        weightingBasisKpiName
        unitType
        measurementUnit
        customUnitLabel
        annualTarget
        weight
        quarterlyAggregationMethod
        plannedContributionWeight
        quarterNumber
        timeline
        originalTarget
        carryIn
        effectiveTarget
        directBasisTarget
        managerOriginalTarget
        managerCarryIn
        managerEffectiveTarget
        teamOriginalTarget
        teamCarryIn
        teamEffectiveTarget
        planStatus
        directActual
        directAchievementRate
        directAchievementRateExact
        aggregateActual
        aggregateActualExact
        aggregationNumeratorExact
        aggregationDenominatorExact
        rollupNumeratorExact
        rollupDenominatorExact
        finalActualExact
        finalActualDecimal
        formulaCalculationStatus
        formulaNumeratorExact
        formulaNumeratorDecimal
        formulaDenominatorExact
        formulaDenominatorDecimal
        formulaResultExact
        formulaResultDecimal
        formulaCalculationVersion
        aggregateAchievementRate
        aggregateAchievementRateExact
        actual
        achievementRate
        achievementRateExact
        annualContribution
        annualContributionExact
        carryOut
        managerCarryOut
        teamCarryOut
        resultStatus
        calculatedAt
        finalizedAt
      }
      totalItems
      currentPage
      itemsPerPage
      totalPages
    }
  }
`;
